# Generated by Django 6.0.6 on 2026-07-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerte',
            options={'ordering': ['statut', '-date_alerte']},
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='est_lue',
        ),
        migrations.AddField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRAITEE', 'Traitée')], default='ACTIVE', max_length=10),
        ),
    ]
