# Generated by Django 6.0.6 on 2026-07-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_animal_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insemination', models.DateField()),
                ('date_misebas_prevue', models.DateField(blank=True, null=True)),
                ('date_misebas_reelle', models.DateField(blank=True, null=True)),
                ('mere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Reproduction',
                'verbose_name_plural': 'Reproductions',
                'ordering': ['-date_insemination'],
            },
        ),
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('animal_enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naissances', to='animals.animal')),
                ('reproduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naissances', to='reproduction.reproduction')),
            ],
            options={
                'verbose_name': 'Naissance',
                'verbose_name_plural': 'Naissances',
                'ordering': ['-date_naissance'],
            },
        ),
    ]
