# Generated by Django 6.0.6 on 2026-07-18 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umero_identification', models.CharField(max_length=50, unique=True)),
                ('espece', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('poids', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('VENDU', 'Vendu'), ('DECEDE', 'Décédé'), ('MALADE', 'Malade')], default='ACTIF', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
