# Generated by Django 6.0.6 on 2026-07-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='umero_identification',
            new_name='numero_identification',
        ),
    ]
