# Generated by Django 6.0.6 on 2026-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_umero_identification_animal_numero_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
