# Generated by Django 6.0.6 on 2026-07-10 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='date_action',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='details',
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PROFILE_UPDATE', 'Modification du profil')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='users.historique')),
            ],
        ),
    ]
