# Generated by Django 6.0.6 on 2026-07-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_umero_identification_animal_numero_identification'),
        ('users', '0002_remove_historique_date_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueaction',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_actions', to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='type_action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PROFILE_UPDATE', 'Modification du profil'), ('ANIMAL_CREATE', 'Ajout d’un animal'), ('ANIMAL_UPDATE', 'Modification d’un animal'), ('ANIMAL_DELETE', 'Suppression d’un animal'), ('STATUS_CHANGE', 'Changement de statut'), ('WEIGHT_UPDATE', 'Modification du poids'), ('PHOTO_UPDATE', 'Modification de la photo')], max_length=30),
        ),
    ]
