# Generated by Django 6.0.6 on 2026-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historiqueaction_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueaction',
            name='type_action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PROFILE_UPDATE', 'Modification du profil'), ('ANIMAL_CREATE', 'Ajout d’un animal'), ('ANIMAL_UPDATE', 'Modification d’un animal'), ('ANIMAL_DELETE', 'Suppression d’un animal'), ('STATUS_CHANGE', 'Changement de statut'), ('WEIGHT_UPDATE', 'Modification du poids'), ('PHOTO_UPDATE', 'Modification de la photo'), ('AJOUT_VACCINATION', 'Ajout d’une vaccination'), ('AJOUT_MALADIE', 'Ajout d’une maladie'), ('AJOUT_TRAITEMENT', 'Ajout d’un traitement'), ('AJOUT_VISITE_VETERINAIRE', 'Ajout d’une visite vétérinaire'), ('MODIFICATION_VACCINATION', 'Modification d’une vaccination'), ('MODIFICATION_MALADIE', 'Modification d’une maladie'), ('MODIFICATION_TRAITEMENT', 'Modification d’un traitement'), ('MODIFICATION_VISITE_VETERINAIRE', 'Modification d’une visite vétérinaire')], max_length=100),
        ),
    ]
